# _config.yml
title: Shubham Tomar
description: A collection of thoughts
url: ""
author: Shubham Tomar
permalink: /:categories/:year/:month/:day/:title/
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-paginate
paginate: 10
paginate_path: "/page/:num/"
